name: Draft Release

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  draft-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: ðŸ“£ Draft Release Notes
        id: release_draft
        uses: .github/actions/release
        with:
          azure_openai_endpoint: ${{ secrets.STRATUS_AZURE_OPENAI_API_ENDPOINT }}
          azure_openai_deployment_name: gpt-4o
          azure_openai_api_version: 2024-10-21
          azure_client_id: ${{ secrets.STRATUS_AZURE_OPENAI_CLIENT_ID }}
          azure_tenant_id: ${{ secrets.STRATUS_AZURE_OPENAI_TENANT_ID }}
          azure_subscription_id: ${{ secrets.STRATUS_AZURE_OPENAI_SUBSCRIPTION_ID }}
          draft: true
          prerelease: true
          append_context: "This repository is a monorepo containing multiple GitHub Actions composite actions, organized under the .github/actions folder, with each action in its own subfolder. If multiple actions are updated in the same release, the Release Notes should categorize updates, improvments and bug fixes per composite action."

      - name: Comment Release Notes on PR
        if: ${{ github.event_name == 'pull_request' && steps.release_draft.outputs.release_notes_base64 != '' }}
        uses: actions/github-script@v7
        with:
          script: |
            const releaseBody = Buffer.from('${{ steps.release_draft.outputs.release_notes_base64 }}', 'base64').toString();
            
            await github.rest.issues.createComment({
              owner: '${{ github.repository_owner }}',
              repo: '${{ github.repository }}'.split('/')[1],
              issue_number: ${{ github.event.pull_request.number }},
              body: `## 📝 Generated Release Notes Preview\n\n${releaseBody}\n\nYou can review and edit these release notes in the draft release.`
            });